### ISSUE TITLE
singleSpaReact mount resolving promise with number instead of component

### ISSUE THREAD

**Issue by alejandrolacasa** [CanopyTax/single-spa-react#36]
Hi!

In the [single-spa-portal-example](https://github.com/me-12/single-spa-portal-example) repo, inside the react project, the mount code fails if the project dependencies are resolved with YARN (or package-lock.json is ignored, and dependencies are installed _from scratch_).

Since v2.5.0 of *single-spa-react*, the mount function is not returning the component anymore, but a number.

v2.4.x can be used in the meantime.

```
export function mount(props) {
  return reactLifecycles.mount(props).then(rootComponent => {
    // rootComponent value is a number, so rootComponent.setStore(...) fails :(
    rootComponent.setStore(props.customProps.store);
    rootComponent.setGlobalEventDistributor(
      props.customProps.globalEventDistributor,
    );
  });
}
```

**Comment by nicholascm90** [comment]
@alejandrolacasa Just faced the exact same issue while working on a prototype with react / angular 1.

**Comment by joeldenning** [comment]
cc @me-12 

The code for single-spa-portal-example was depending on an undocumented feature of single-spa-react (the resolved value of the `mount` lifecycle) that changed when I added support for parcels in single-spa-react@2.5.0. Since it's undocumented, I didn't expect anyone to notice the change, but clearly was mistaken :)

I looked into changing single-spa-react to behave like it used to in <=2.4.0, but then saw that the undocumented feature that single-spa-portal-example was depending on was completely unnecessary. So instead, I've created https://github.com/me-12/single-spa-portal-example/pull/27 which will fix single-spa-portal-example's usage of single-spa-react to not depend on what the `mount` lifecycle resolves.

@alejandrolacasa and @nicholascm90 -- if you make the same code changes as I have done in that PR to portal example, it should fix everything. Feel free to reopen if there are further issues!

**Comment by me-12** [comment]
Thanks @joeldenning, PR is merged.
