### ISSUE TITLE
single-spa-react must be passed opts.rootComponent or opts.loadRootComponent

### ISSUE THREAD

**Issue by bernardbaker** [CanopyTax/single-spa-react#54]
I'm working with the single-spa-react library and I'm getting the following error:

`Uncaught error: Application 'error' died in status LOADING_SOURCE_CODE: single-spa-react must be passed opts.rootComponent or opts.loadRootComponent`

The code for the spa app is:

    import React from "react";
    import ReactDOM from "react-dom";
    import singleSpaReact from "single-spa-react";
    import Page from "@btab/front-end-microservices-bernard-baker-404-page";
    
    function domElementGetter() {
      return document.getElementById("error");
    }
    
    export const app = singleSpaReact({
      React,
      ReactDOM,
      rootComponent: Page,
      domElementGetter
    });

You can access the NPM package [here](https://www.npmjs.com/package/@btab/front-end-microservices-bernard-baker-404-page).
And the GitHub [here](https://github.com/bernardbaker/front-end-microservices-bernard-baker-404-page) 

The single spa config file is listed below: 

    import { registerApplication, start } from "single-spa";
    
    registerApplication(
      "error",
      () => import("./src/error/error.app.js").then(module => module.app),
      () => true
    );

Any help with that error would be appreciated.

Thanks,
Bernard

**Comment by joeldenning** [comment]
Your github repo is empty on the master branch, except for a Readme. And there are no other branches. But I was able to find your code at https://unpkg.com/@btab/front-end-microservices-bernard-baker-404-page@0.2.3/dist and take a look at it.

The reason your code is not working is because `Page` is not defined. If you put in a console.log() before calling single-spa-react, you'll see that it's either null or undefined. The reason it's not defined is because you're importing it wrong. You have exported it as a named export instead of the default export.

Your code (which I can't find because it's not in the npm published artifact) must have this in it:

```js
export class App extends React.Component {
}
```

which means you should import it this way:

```js
import React from "react";
import ReactDOM from "react-dom";
import singleSpaReact from "single-spa-react";
import { App } from "@btab/front-end-microservices-bernard-baker-404-page";

function domElementGetter() {
  return document.getElementById("error");
}

export const app = singleSpaReact({
  React,
  ReactDOM,
  rootComponent: Page,
  domElementGetter
});
```

Notice the `import { App }` instead of `import Page`.

The other way to fix it would be to `export default class App` instead of `export class App`, and then you can keep the `import Page from '...'`

Hope this helps. Gonna close but feel free to comment further or reopen if that wasn't it.

**Comment by bernardbaker** [comment]
Hi @joeldenning, thanks for answering my question. You have resolved my issue. It was an import error.
